name: Release
on:
  push: { tags: "v[0-9]+.[0-9]+.[0-9]+*" }
  workflow_dispatch:

permissions: {}
jobs:
  release:
    permissions: { contents: write, id-token: write }
    uses: nodenv/.github/.github/workflows/release.yml@v7
    with:
      homebrew: false
